# Site settings
title: Sina Balkhi
email: 20431332+sinablk@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Sina Balkhi's Personal Blog
baseurl: "/"
url: "https://sinablk.github.io"
author: Sina Balkhi
github_username: sinablk
logo: "/assets/favicon.png"

# Social media linke for jekyll-seo-tag
social:
  name: Sina Balkhi
  links:
    - https://github.com/sinablk
    - https://linkedin/in/sinablk

# Build settings
markdown: kramdown
highlighter: rouge # But these styles are overridden?

# Markdown Processors (defaults)
#rdiscount:
#  extensions        : []

#redcarpet:
#  extensions        : []

# Pagination settings
paginate: 5
paginate_path: "/posts/page:num"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# SASS minify
sass:
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
